package(default_visibility = ["//app/..."])

export_file(
    name = "dockerfile",
    src = "Dockerfile",
)

export_file(
    name = "deployment",
    src = "deployment.yaml",
)

export_file(
    name = "service",
    src = "service.yaml",
)
